if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("MWChatViewerChatVisibilityHookQuery_facebookRelayOperation",[],(function(a,b,c,d,e,f){e.exports="2353962864732251"}),null);
__d("MWChatViewerChatVisibilityHookQuery.graphql",["MWChatViewerChatVisibilityHookQuery_facebookRelayOperation"],(function(a,b,c,d,e,f){"use strict";a=function(){var a=[{alias:null,args:null,concreteType:"Viewer",kind:"LinkedField",name:"viewer",plural:!1,selections:[{alias:null,args:null,kind:"ScalarField",name:"chat_visibility",storageKey:null}],storageKey:null}];return{fragment:{argumentDefinitions:[],kind:"Fragment",metadata:null,name:"MWChatViewerChatVisibilityHookQuery",selections:a,type:"Query",abstractKey:null},kind:"Request",operation:{argumentDefinitions:[],kind:"Operation",name:"MWChatViewerChatVisibilityHookQuery",selections:a},params:{id:b("MWChatViewerChatVisibilityHookQuery_facebookRelayOperation"),metadata:{},name:"MWChatViewerChatVisibilityHookQuery",operationKind:"query",text:null}}}();e.exports=a}),null);
__d("useForceUpdate",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useReducer;function a(){var a=h(function(a){return a+1},0);a[0];a=a[1];return a}g["default"]=a}),98);
__d("useCopyText",["DateConsts","clearTimeout","react","requireDeferred","setTimeout","useForceUpdate"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useCallback,i=b.useEffect,j=b.useRef,k=b.useState,l=c("requireDeferred")("Clipboard").__setRef("useCopyText"),m=null;l.onReady(function(a){m=a});function a(a){var b=a.onCopyPress,e=a.value;a=k(!1);var f=a[0],g=a[1],n=j(null),o=m!=null&&m.isSupported(),p=m,q=c("useForceUpdate")();i(function(){if(p==null)if(m==null)return l.onReady(q).remove;else q()},[p,q]);a=h(function(){b!=null&&b();if(o&&typeof e==="string"){var a;a=(a=m)==null?void 0:a.copy(e);a===!0&&(g(!0),c("clearTimeout")(n.current),n.current=c("setTimeout")(function(){g(!1)},.75*d("DateConsts").MS_PER_SEC))}},[b,n,e,o]);return[o,f,a]}g["default"]=a}),98);
__d("MDSCircleButton.react",["BaseTheme.react","TetraCircleButton.react","react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react"),i={red:"#FF443D"};function j(a){return a==null?"":i[a]}function a(a,b){var d=a.buttonColor;a=babelHelpers.objectWithoutPropertiesLoose(a,["buttonColor"]);d={dark:{"secondary-button-background":j(d)},light:{"secondary-button-background":j(d)},type:"VARIABLES"};return h.jsx(c("BaseTheme.react"),{config:d,children:h.jsx(c("TetraCircleButton.react"),babelHelpers["extends"]({iconRatio:"large"},a,{ref:b}))})}a.displayName=a.name+" [from "+f.id+"]";b=h.forwardRef(a);g["default"]=b}),98);
__d("MWCMInboxHeaderCommunityGroupName.bs",["ReQL.bs","ReQLSubscription.bs","bs_curry","react","useReStore"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function i(a){return a}function a(a){var c=a.thread;a=a.renderWrapper;a=a!==void 0?a:i;var d=b("useReStore")(),e=b("ReQLSubscription.bs").useFirst(h.useMemo(function(){return b("ReQL.bs").getKeyRange(b("ReQL.bs").fromTableAscending(d.table("community_folders")),{hd:c.parentThreadKey,tl:0})},[d,JSON.stringify(c.parentThreadKey)]));if(e!==void 0)return h.jsx(h.Fragment,{children:b("bs_curry")._1(a,e.name)});else return null}c=a;f.defaultRenderWrapper=i;f.make=c}),null);
__d("MAWDualSendSimplePermissionsManager.bs",["MAWGating.bs"],(function(a,b,c,d,e,f){"use strict";function g(a){if(b("MAWGating.bs").isDualSendCrossApp(void 0))return!0;else return b("MAWGating.bs").isDualSendWebOrCrossApp(void 0)}function a(a){if(g(void 0))return b("MAWGating.bs").isDualSendMediaEnabled(void 0);else return!1}function c(a){return b("MAWGating.bs").isGroupDualSendTextEnabled(void 0)}function d(a){return b("MAWGating.bs").isGroupDualSendMediaEnabled(void 0)}function e(a){if(b("MAWGating.bs").isGroupDualSendTextEnabled(void 0))return!0;else return b("MAWGating.bs").isGroupDualSendMediaEnabled(void 0)}f.isDualSendUser=g;f.isDualSendMediaUser=a;f.isGroupDualSendTextUser=c;f.isGroupDualSendMediaUser=d;f.isGroupDualSendUser=e}),null);
__d("MWChatViewerChatVisibilityHook",["CometRelay","MWChatViewerChatVisibilityHookQuery.graphql"],(function(a,b,c,d,e,f,g){"use strict";var h,i=h!==void 0?h:h=b("MWChatViewerChatVisibilityHookQuery.graphql");function a(){var a=d("CometRelay").useLazyLoadQuery(i,{},{fetchPolicy:"store-or-network"});return(a==null?void 0:(a=a.viewer)==null?void 0:a.chat_visibility)===!0}g["default"]=a}),98);
__d("MWChatTypingIndicator.bs",["react","stylex"],(function(a,b,c,d,e,f){"use strict";var g,h,i=g||b("react");c="rqt66bd7-B";var j={root:{alignItems:"bp9cbjyn",display:"j83agx80",height:"kmzbrmfl"},dot:{animationName:"d75kxgp9",animationDuration:"kv069q7b",animationIterationCount:"ee40wjg4",animationTimingFunction:"rr7aif1o",borderTopStartRadius:"s8bnoagg",borderTopEndRadius:"bn9qtmzc",borderBottomEndRadius:"hp05c5td",borderBottomStartRadius:"b6jg2yqc",display:"q9uorilb",height:"mw227v9j",marginEnd:"ditlmg2l",marginStart:"nvdbi5me",width:"loos5mxf",backgroundColor:"aph9nnby"},dot1:{animationDelay:"tv4077gy"},dot2:{animationDelay:"oeefd0zo"},dot3:{animationDelay:"dg03pwpq"}};function a(a){return i.jsxs("div",{className:(h||(h=b("stylex")))(j.root),children:[i.jsx("div",{className:h(j.dot,j.dot1)}),i.jsx("div",{className:h(j.dot,j.dot2)}),i.jsx("div",{className:h(j.dot,j.dot3)})]})}d=a;f.dotAnimation=c;f.styles=j;f.make=d}),null);
__d("LSAuthorityLevel.bs",[],(function(a,b,c,d,e,f){"use strict";a=[0,20];b=[0,40];c=[0,60];d=[0,75];e=[0,80];var g=[0,100];f.optimistic=a;f.clientPartial=b;f.serverPartial=c;f.authoritativePendingReplacement=d;f.authoritative=e;f.clientAuthoritativeDelete=g}),null);
__d("LSContactIdType.bs",["bs_caml_int64"],(function(a,b,c,d,e,f){"use strict";a=b("bs_caml_int64").zero;c=b("bs_caml_int64").one;d=[0,2];f.unknown=a;f.fbid=c;f.smsLocalId=d}),null);
__d("MWV2EnsureThatChatTabExists.bs",["LS.bs","LSAuthorityLevel.bs","LSContactBlockedByViewerStatus.bs","LSContactGender.bs","LSContactIdType.bs","LSContactType.bs","LSContactViewerRelationship.bs","LSContactWorkForeignEntityType.bs","LSDatabaseType.bs","LSMessagingThreadTypeUtil.bs","LSTransaction.bs","LSVerifyContactRowExists","LSVerifyThreadRowExists","Promise","bs_curry","cr:2889","promiseDone","react","useReStore"],(function(a,b,c,d,e,f){"use strict";var g,h=g||b("react");function a(a,c){var d=b("useReStore")();h.useEffect(function(){var e=function(e){if(b("LSMessagingThreadTypeUtil.bs").isOneToOne(c))return b("LSTransaction.bs").run(d,function(c){return b("LSVerifyContactRowExists")(a,b("LSContactIdType.bs").fbid,void 0,void 0,b("LSContactType.bs").user,void 0,void 0,void 0,void 0,!1,!1,b("LSContactBlockedByViewerStatus.bs").unblocked,void 0,!1,b("LSAuthorityLevel.bs").clientPartial,void 0,void 0,b("LSContactWorkForeignEntityType.bs").unknown,b("LSContactGender.bs").unknown,b("LSContactViewerRelationship.bs").unknown,void 0,b("LS.bs").make(c))},"readWrite");else return b("Promise").resolve(void 0)};b("promiseDone")(e(void 0).then(function(e){return!(b("cr:2889")==null)&&b("LSMessagingThreadTypeUtil.bs").isSecure(c)?b("bs_curry")._2(b("cr:2889").call,d,a):b("LSTransaction.bs").run(d,function(d){return b("LSVerifyThreadRowExists")(a,c,b("LSDatabaseType.bs").mailbox,b("LS.bs").make(d))},"readWrite")}),void 0,void 0)},[d,JSON.stringify(a),JSON.stringify(c)])}c=b("cr:2889");f.$MAWVerifyExistingThreadExists$requireCondXplat=b("cr:2889");f.mawVerifyExistingThreadExists=c;f.useHook=a}),null);
__d("CometEmoji.bs",["CometEmoji.react"],(function(a,b,c,d,e,f){"use strict";a=b("CometEmoji.react");f.make=a}),null);
__d("EmojiFormat.bs",[],(function(a,b,c,d,e,f){"use strict";function g(a){return a.split("_").map(function(a){return parseInt(a,16)})}function a(a){return a.map(function(a){return a.toString(16)}).join("_")}function h(a){return a.map(function(a){return String.fromCodePoint(a)}).join("")}function b(a){return h(g(a))}f.codeStringToCodeArray=g;f.codeArrayToCodeString=a;f.codeArrayToUnicode=h;f.codeStringToUnicode=b}),null);
__d("EmojiLikeConstants",["EmojiStaticConfig"],(function(a,b,c,d,e,f,g){"use strict";a=Object.freeze({XSMALL:"xsmall",SMALL:"small",MEDIUM:"medium",LARGE:"large"});b={dp16:"xsmall",dp32:"small",dp64:"medium",db64:"medium",dp128:"large"};d=Object.freeze({PICKER:"picker",HOT_LIKE:"hot_like"});e=[983040];f="hot_emoji_source";var h="hot_emoji_size",i="emoji_like",j="\ud83d\udc4d",k=[128077];g.sizeMap=c("EmojiStaticConfig").sizeMap;g.size=a;g.sizeMapTransfer=b;g.source=d;g.FB_THUMBS_UP_EMOJI=e;g.SOURCE_TAG_PREFIX=f;g.TAG_PREFIX_NEW=h;g.TAG_PREFIX_OLD=i;g.THUMBS_UP_EMOJI=j;g.THUMBS_UP_EMOJI_CODES=k}),98);
__d("MercuryLocalIDs",["randomInt"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return"root:"+h(a)}function h(a){a=a!=null?a:Date.now();var b=c("randomInt")(0,4294967295);b=("0000000000000000000000"+b.toString(2)).slice(-22);a=a.toString(2)+b;return i(a.slice(-63))}function i(a){var b="";a=a;while(a!="0"){var c=0,d="";for(var e=0;e<a.length;e++)c=2*c+parseInt(a[e],10),c>=10?(d+="1",c-=10):d+="0";b=c.toString()+b;a=d.slice(d.indexOf("1"))}return b}g.generateThreadID=a;g.generateOfflineThreadingID=h}),98);
__d("memoizeByIdentity",[],(function(a,b,c,d,e,f){"use strict";function a(a){var b=new Map();return function(c){b.has(c)||b.set(c,a.call(this,c));return b.get(c)}}f["default"]=a}),66);
__d("useDebounced",["debounce","react"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useEffect,i=b.useMemo,j=b.useRef;function a(a,b,d){b===void 0&&(b=100);d===void 0&&(d=!1);var e=j(a);h(function(){e.current=a},[a]);var f=i(function(){return c("debounce")(function(){return e.current.apply(e,arguments)},b,null,!1,d)},[b,d]);h(function(){return f.reset},[f]);return f}g["default"]=a}),98);
__d("useUniqueID",["react","uniqueID"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react").useRef;function a(){var a=h(null);a.current===null&&(a.current=c("uniqueID")());return a.current}g["default"]=a}),98);
__d("useLexicalIsTextContentEmpty",["cr:1022"],(function(a,b,c,d,e,f){e.exports=b("cr:1022")}),null);
/**
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE file in the root directory of this source tree.
*
* @noflow
* @nolint
* @preventMunge
* @preserve-invariant-messages
* @generated
* @preserve-whitespace
* @fullSyntaxTransform
 */__d("useLexicalIsTextContentEmpty.prod",["LexicalText","react"],(function $module_useLexicalIsTextContentEmpty_prod(global,require,requireDynamic,requireLazy,module,exports){var c_react;
var e=c_react||(c_react=require("react")),f="undefined"!==typeof window&&"undefined"!==typeof window.document&&"undefined"!==typeof window.document.createElement?e.useLayoutEffect:e.useEffect;module.exports=function(a,c){var _e$useState=e.useState(a.getEditorState().read(require("LexicalText").$isRootTextContentEmptyCurry(a.isComposing(),c))),g=_e$useState[0],h=_e$useState[1];f(function(){return a.registerUpdateListener(function(_ref){var d=_ref.editorState;var k=a.isComposing();d=d.read(require("LexicalText").$isRootTextContentEmptyCurry(k,c));h(d);});},[a,c]);return g;};}),null);