if (self.CavalryLogger) { CavalryLogger.start_js_script(document.currentScript); }/*FB_PKG_DELIM*/

__d("MWGroupMembershipListItem.bs",[],(function(a,b,c,d,e,f){"use strict";function a(a){if(a.TAG===0)return a._0.isAdmin;else return a._0.isAdmin}function b(a){if(a.TAG===0)return a._1.id;else return a._0.contactId}f.isAdmin=a;f.contactId=b}),null);
__d("isFacebookishURI",["isFacebookURI","isMessengerDotComURI"],(function(a,b,c,d,e,f,g){"use strict";function a(a){return c("isFacebookURI")(a)||c("isMessengerDotComURI")(a)}g["default"]=a}),98);
__d("ZenonAbstractButton.react",["react"],(function(a,b,c,d,e,f,g){"use strict";var h=d("react");function a(a,b){var c=a["aria-label"],d=a.children,e=a["data-hover"],f=a.disabled;f=f===void 0?!1:f;var g=a.label,j=a.onClick,k=a.showLabelWhenDisabled;k=k===void 0?!1:k;a=babelHelpers.objectWithoutPropertiesLoose(a,["aria-label","children","data-hover","disabled","label","onClick","showLabelWhenDisabled"]);return h.jsxs("button",babelHelpers["extends"]({"aria-disabled":f,"aria-label":c,"data-hover":f&&!k?"none":e,disabled:f&&!k,onClick:f?i:j,ref:b,type:"button"},a,{children:[d,h.jsx("span",{className:"lanauo1g ah27w7js alrytcbg hgsucude rb9yzgxv mc69vkn9 sqk0u2jd",children:g})]}))}a.displayName=a.name+" [from "+f.id+"]";function i(a){a.preventDefault()}b=h.forwardRef(a);g["default"]=b}),98);
__d("ZenonLoggingSurfaceContext",["react"],(function(a,b,c,d,e,f,g){"use strict";a=d("react");b=a.createContext("call_container");g["default"]=b}),98);
__d("RTCPeerConnection",[],(function(a,b,c,d,e,f){"use strict";a=window.RTCPeerConnection||window.mozRTCPeerConnection||window.webkitRTCPeerConnection;f["default"]=a}),66);
__d("ZenonSignalingTransportTypes",[],(function(a,b,c,d,e,f){"use strict";a=Object.freeze({CHILD_WINDOW_READY:"rtc_child_window_ready",PARENT_INITIATED_CALL:"rtc_child_window_start_call",PARENT_TO_CHILD_MESSAGE:"rtc_child_window_message"});f.ChildTransportMessageType=a}),66);
__d("ZenonIsUnifiedRoomsAtom",["Recoil"],(function(a,b,c,d,e,f,g){"use strict";a=d("Recoil").atom({"default":!1,key:"ZenonIsUnifiedRoomsAtom"});g["default"]=a}),98);
__d("getGenderConst",["GenderConst"],(function(a,b,c,d,e,f,g){"use strict";function a(a){switch(a){case"FEMALE":return c("GenderConst").FEMALE_SINGULAR;case"MALE":return c("GenderConst").MALE_SINGULAR;case"NEUTER":return c("GenderConst").NEUTER_SINGULAR;case"UNKNOWN":default:return c("GenderConst").UNKNOWN_SINGULAR}}g["default"]=a}),98);
__d("useContentRect",["react","useResizeObserver"],(function(a,b,c,d,e,f,g){"use strict";b=d("react");var h=b.useCallback,i=b.useState;function a(){var a=i(),b=a[0],d=a[1];a=h(function(a){return d(a)},[]);a=c("useResizeObserver")(a);return[b,a]}g["default"]=a}),98);